locarise_drf_oauth2_support/oauth2_client/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib.auth.views import LoginView, LogoutView

from .views import OAuthObtainAuthToken, ObtainAuthToken

template_name = "oauth2_client/login.html"

next_page = "/"

auth_patterns = [
    # API Views
    url(r"^token", ObtainAuthToken.as_view(), name="token"),
    url(
        r"^oauth2/(?P<backend_name>[^/]+)/token$",
        OAuthObtainAuthToken.as_view(),
        name="oauth2-token",
    ),
    # Browsable API Views
    url(r"^login$", LoginView.as_view(template_name=template_name), name="login"),
    url(r"^logout$", LogoutView.as_view(template_name=next_page), name="logout"),
]

urlpatterns = [
    url("", include(("social_django.urls", "rest_framework"), namespace="social")),
    url(
        r"^auth/",
        include((auth_patterns, "rest_framework"), namespace="rest_framework"),
    ),
]

locarise_drf_oauth2_support/users/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import CurrentUserView


urlpatterns = [
    url(r'^me$', CurrentUserView.as_view(), name='me')
]

locarise_drf_oauth2_support/users/models.py
# -*- coding: utf-8 -*-

from shortuuidfield import ShortUUIDField

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    BaseUserManager,
)
from django_extensions.db.fields import ModificationDateTimeField, CreationDateTimeField
from simple_history.models import HistoricalRecords

try:
    from django.contrib.postgres.fields import JSONField
except ImportError:  # pragma: no cover
    from jsonfield import JSONField


from .utils import sane_repr


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, uid=None, **extra_fields):

        extra_fields.pop("username", None)

        if not email:
            raise ValueError("Users must have an email address")

        if uid:
            user, _ = self.model.objects.get_or_create(uid=uid)
        else:
            user, _ = self.model.objects.get_or_create(email=email)

        user.email = email

        for field, value in extra_fields.items():
            setattr(user, field, value)

        user.set_password(password)
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """
    Users within the Django authentication system are represented by
    this model.
    """

    # Fields from SAMS
    uid = ShortUUIDField(primary_key=True, editable=False)
    email = models.EmailField(unique=True, max_length=254)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    locale = models.CharField(max_length=5)
    organizations = JSONField(null=True)

    # Local fields
    created_at = CreationDateTimeField()
    updated_at = ModificationDateTimeField()

    objects = UserManager()

    USERNAME_FIELD = "email"

    history = HistoricalRecords()

    __repr__ = sane_repr("email",)

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """
        Returns the short name for the user.
        """
        return self.first_name

locarise_drf_oauth2_support/oauth2_client/views.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.contrib.auth import get_user_model
from django.http import Http404

from rest_framework.authtoken.models import Token

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, parsers, renderers, permissions

from social_core.backends.utils import get_backend
from social_core.exceptions import MissingBackend

from .serializers import AuthTokenSerializer, AccessTokenSerializer


User = get_user_model()


class ObtainAuthToken(APIView):
    """
    This authentication scheme uses a simple token-based HTTP Authentication
    scheme.

    For clients to authenticate, the token key should be included in the
    `Authorization` HTTP header. The key should be prefixed by the string
    literal "Token", with whitespace separating the two strings. For example:

        Authorization: Token abc123

    Unauthenticated responses that are denied permission will result in an
    `HTTP 401` Unauthorized response with an appropriate WWW-Authenticate
    header.
    """
    throttle_classes = ()
    permission_classes = (permissions.AllowAny,)
    parser_classes = (parsers.FormParser, parsers.MultiPartParser,
                      parsers.JSONParser,)
    renderer_classes = (renderers.JSONRenderer,)
    serializer_class = AuthTokenSerializer
    model = Token
    queryset = Token.objects.none()

    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            token, created = Token.objects.get_or_create(
                user=serializer.validated_data['user']
            )
            return Response({'token': token.key})
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class OAuthObtainAuthToken(APIView):
    """
    This authentication scheme uses the oauth2 access token from the given
    authentication backend to authenticate the user.
    """
    throttle_classes = ()
    permission_classes = (permissions.AllowAny,)
    parser_classes = (parsers.FormParser, parsers.MultiPartParser,
                      parsers.JSONParser,)
    renderer_classes = (renderers.JSONRenderer,)
    serializer_class = AccessTokenSerializer
    model = Token
    queryset = Token.objects.none()

    def get_backend_instance(self, name=None, strategy=None):
        try:
            backend = get_backend(
                backends=settings.AUTHENTICATION_BACKENDS,
                name=name
            )
        except MissingBackend:
            raise Http404
        return backend(strategy=strategy)

    def post(self, request, backend_name, *args, **kwargs):
        backend = self.get_backend_instance(name=backend_name)

        serializer = self.serializer_class(
            data=request.data,
            backend=backend
        )
        if serializer.is_valid():
            token, created = Token.objects.get_or_create(
                user=serializer.validated_data['user']
            )
            return Response({'token': token.key})

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

locarise_drf_oauth2_support/users/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth import get_user_model
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated

from .serializers import CurrentUserSerializer

User = get_user_model()


class CurrentUserView(generics.RetrieveAPIView):
    """
    Retrieve authenticated user information.
    """

    queryset = User.objects.none()
    serializer_class = CurrentUserSerializer
    permission_classes = (IsAuthenticated,)

    def get_object(self, *args, **kwargs):
        return self.request.user

locarise_drf_oauth2_support/oauth2_client/templates/oauth2_client/login.html
{% extends "rest_framework/base.html" %}
{% load staticfiles %}
{% load rest_framework %}

{% block body %}
<body class="container">
<div class="container-fluid" style="margin-top: 30px">
    <div class="row-fluid">
        <div class="well"
             style="width: 320px; margin-left: auto; margin-right: auto">
            <div class="row-fluid">
                <div class="text-center">
                    {% block branding %}
                    <h3 style="margin: 0 0 20px;">
                        Locarise API Login
                    </h3>
                    {% endblock %}
                </div>
            </div><!-- /row fluid -->

            <div class="row-fluid">
                {% if debug %}
                <div>
                    <form action="{% url 'rest_framework:login' %}?next={{ next }}" role="form"
                          method="post">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}"/>

                        <div id="div_id_username"
                             class="clearfix control-group {% if form.username.errors %}error{% endif %}">
                            <div class="form-group">
                                <label for="id_username">Username:</label>
                                <input type="text" name="username"
                                       maxlength="100"
                                       autocapitalize="off"
                                       autocorrect="off"
                                       class="form-control textinput textInput"
                                       id="id_username" required
                                       {% if form.username.value
                                       %}value="{{ form.username.value }}" {%
                                       endif %}>
                                {% if form.username.errors %}
                                <p class="text-error">
                                    {{ form.username.errors|striptags }}
                                </p>
                                {% endif %}
                            </div>
                        </div>

                        <div id="div_id_password"
                             class="clearfix control-group {% if form.password.errors %}error{% endif %}">
                            <div class="form-group">
                                <label for="id_password">Password:</label>
                                <input type="password" name="password"
                                       maxlength="100" autocapitalize="off"
                                       autocorrect="off"
                                       class="form-control textinput textInput"
                                       id="id_password" required>
                                {% if form.password.errors %}
                                <p class="text-error">
                                    {{ form.password.errors|striptags }}
                                </p>
                                {% endif %}
                            </div>
                        </div>

                        {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                        <div class="well well-small text-error"
                             style="border: none">{{ error }}
                        </div>
                        {% endfor %}
                        {% endif %}

                        <div class="form-actions-no-box">
                            <input type="submit" name="submit" value="Log in"
                                   class="btn btn-primary form-control"
                                   id="submit-id-submit">
                        </div>
                    </form>
                </div>
                {% endif %}

                <div align="center">
                    <a class="btn btn-default btn-large locarise"
                       href="{% url 'social:begin' 'locarise-oauth2' %}?next={{ next }}">
                        <img src="{% static 'img/logo-full.svg' %}">
                        Locarise Login
                    </a>
                </div>

            </div><!-- /.row-fluid -->
        </div><!--/.well-->
    </div><!-- /.row-fluid -->
</div><!-- /.container-fluid -->
</body>
{% endblock %}